### ISSUE TITLE
Major issue

### ISSUE THREAD

**Issue by FabioGaming** [altamino/api#1]
There is a Major issue this API is having, Python....

**Comment by imperialwool** [comment]
do we really need to rewrite all project to another language just because its python
cant we really just continue on python

**Comment by FabioGaming** [comment]
C SHARP AAAAARGHHH C SHAAAARP ASP.NEEEET EASYYYYYYYYY CONTROLLER STRUCTURE EF CORE FOR DATABASE DRIVERRRR ITS EASY AND BETTERRRRRR
FROMBODY ATTEIBUUUUTEEEE MIDDLEWAARE

**Comment by imperialwool** [comment]
nope, i dont wanna touch c#
i cant see any reason to use c# while we have golang

**Comment by FabioGaming** [comment]
Golang has ass error handling and ASP.NET is superior
