### ISSUE TITLE
AminoID generation needs to improve

### ISSUE THREAD

**Issue by imperialwool** [altamino/api#2]
AminoID generating from email, it can lead to potencial security issues.
What we need to do is:
- make aminoid generator that not using any login data
- change all aminoids that was affected by generator using new generator

**Comment by AugustLigh** [comment]
maybe someting like a:
aminoId=data['nickname'] + Generator.String()

**Comment by AugustLigh** [comment]
we can try unidecode and re.
example:
text = "Привет, как дела?"
result = unidecode(text)
result = result.replace(" ", "_")
result = re.sub(r'[^A-Za-z0-9_]', '', result)
print(result)  # Privet_kak_dela

**Comment by imperialwool** [comment]
Solved with PR #4
